### ISSUE TITLE
The app becomes frozen due to BlockingQueue

### ISSUE THREAD

**Issue by AndreLee-2019** [smartdevicelink/sdl_java_suite#1110]
### Bug Report
We encountered an ANR issue when we start SDL video streaming. When we called `sdlManager.getVideoStreamManager().startRemoteDisplayStream(...);`
Our app will become frozen sometimes. And we found the state of the main thread is WAITING. Here is the thread dump.

main@12448" prio=5 tid=0x2 nid=NA waiting
java.lang.Thread.State: WAITING
blocks main@12448
at java.lang.Object.wait(Object.java:-1)
at java.lang.Thread.parkFor$(Thread.java:2137)
   locked <0x36f1> (a java.lang.Object)
at sun.misc.Unsafe.park(Unsafe.java:358)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:350)
**at com.smartdevicelink.streaming.StreamPacketizer.sendArrayData(StreamPacketizer.java:275)**
at com.smartdevicelink.streaming.StreamPacketizer.sendFrame(StreamPacketizer.java:218)
at com.smartdevicelink.encoder.VirtualDisplayEncoder$1.onOutputBufferAvailable(VirtualDisplayEncoder.java:243)
at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1699)
at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1646)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6718)
at java.lang.reflect.Method.invoke(Method.java:-1)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

##### Reproduction Steps
1. Build an SDL video streaming sample application and install it on an Android device.
2. Physically connect the USB cable to the TDK.
3. Start streaming to the TDK.
4. Check if the app becomes frozen.
5. Physically disconnect the USB cable.
6. Repeat steps 2~5 several times until the issue happened.

##### Expected Behavior
The app should not become frozen.

##### Observed Behavior
The app becomes frozen.

##### OS & Version Information
* Android Version: Android 9.0 (Pixel 2)
* SDL Android Version: 4.9.0 (It doesn't happen in 4.8.1.)

**Comment by AndreLee-2019** [comment]
This issue doesn't happen in 4.8.1. Does anybody have some clues?

**Comment by AndreLee-2019** [comment]
I have tested with SDL SDK v4.9.1, and it still happened.

**Comment by missingbridge** [comment]
哈哈

**Comment by AndreLee-2019** [comment]
After some tests, the PR can fix this issue in my case. Should I close the issue? Or someone will handle this?

**Comment by joeygrover** [comment]
Hi @AndreLee-2019 we will close the issue when the PR is merged into a mainline branch. Thanks for testing it and glad to hear it fixed the issue for you!
