### ISSUE TITLE
SDL Error observed on stopping Service in SdlManagerListener.onStart

### ISSUE THREAD

**Issue by ashwink11** [smartdevicelink/sdl_java_suite#1172]
### Bug Report
Stopping SdlService in Hello SDL Android App, raise multiple errors

##### Reproduction Steps
1. Call "StopService" code as shown below
![image](https://user-images.githubusercontent.com/24958343/64951318-e66e2300-d87d-11e9-9701-a5029fa96af5.png)
2. Connect to System so, that condition satisfies and "stopService" calls are executed

##### Expected Behavior
Service should stop without any error.

##### Observed Behavior
Below errors observed.

```
2019-09-16 12:25:30.901 16783-16783/com.sdl.hellosdlandroid E/ActivityThread: Service com.sdl.hellosdlandroid.SdlService has leaked IntentReceiver com.smartdevicelink.util.MediaStreamingStatus$1@2d07cf5 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Service com.sdl.hellosdlandroid.SdlService has leaked IntentReceiver com.smartdevicelink.util.MediaStreamingStatus$1@2d07cf5 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1588)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1368)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1515)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1488)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1476)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:627)
        at com.smartdevicelink.util.MediaStreamingStatus.updateBroadcastReceiver(MediaStreamingStatus.java:258)
        at com.smartdevicelink.util.MediaStreamingStatus.listenForIntents(MediaStreamingStatus.java:243)
        at com.smartdevicelink.util.MediaStreamingStatus.setupBluetoothBroadcastReceiver(MediaStreamingStatus.java:211)
        at com.smartdevicelink.util.MediaStreamingStatus.isSupportedAudioDevice(MediaStreamingStatus.java:152)
        at com.smartdevicelink.util.MediaStreamingStatus.isAudioOutputAvailable(MediaStreamingStatus.java:120)
        at com.smartdevicelink.SdlConnection.SdlSession2.isAudioRequirementMet(SdlSession2.java:97)
        at com.smartdevicelink.SdlConnection.SdlSession2.startSession(SdlSession2.java:174)
        at com.smartdevicelink.proxy.SdlProxyBase.initializeProxy(SdlProxyBase.java:1590)
        at com.smartdevicelink.proxy.SdlProxyBase.performBaseCommon(SdlProxyBase.java:998)
        at com.smartdevicelink.proxy.SdlProxyBase.<init>(SdlProxyBase.java:793)
        at com.smartdevicelink.managers.SdlManager$5.<init>(SdlManager.java:593)
        at com.smartdevicelink.managers.SdlManager.start(SdlManager.java:591)
        at com.sdl.hellosdlandroid.SdlService.startProxy(SdlService.java:218)
        at com.sdl.hellosdlandroid.SdlService.onStartCommand(SdlService.java:113)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
        at android.app.ActivityThread.access$1800(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2019-09-16 12:25:30.906 16783-16783/com.sdl.hellosdlandroid E/ActivityThread: Service com.sdl.hellosdlandroid.SdlService has leaked ServiceConnection com.smartdevicelink.transport.TransportBroker$1@3560a8a that was originally bound here
    android.app.ServiceConnectionLeaked: Service com.sdl.hellosdlandroid.SdlService has leaked ServiceConnection com.smartdevicelink.transport.TransportBroker$1@3560a8a that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1805)
        at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1677)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1656)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1721)
        at android.app.ContextImpl.bindService(ContextImpl.java:1650)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
        at com.smartdevicelink.transport.TransportBroker.sendBindingIntent(TransportBroker.java:666)
        at com.smartdevicelink.transport.TransportBroker.registerWithRouterService(TransportBroker.java:644)
        at com.smartdevicelink.transport.TransportBroker.start(TransportBroker.java:430)
        at com.smartdevicelink.transport.TransportManager.start(TransportManager.java:97)
        at com.smartdevicelink.protocol.SdlProtocolBase.start(SdlProtocolBase.java:166)
        at com.smartdevicelink.SdlConnection.SdlSession2.startSession(SdlSession2.java:179)
        at com.smartdevicelink.proxy.SdlProxyBase.initializeProxy(SdlProxyBase.java:1590)
        at com.smartdevicelink.proxy.SdlProxyBase.performBaseCommon(SdlProxyBase.java:998)
        at com.smartdevicelink.proxy.SdlProxyBase.<init>(SdlProxyBase.java:793)
        at com.smartdevicelink.managers.SdlManager$5.<init>(SdlManager.java:593)
        at com.smartdevicelink.managers.SdlManager.start(SdlManager.java:591)
        at com.sdl.hellosdlandroid.SdlService.startProxy(SdlService.java:218)
        at com.sdl.hellosdlandroid.SdlService.onStartCommand(SdlService.java:113)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
        at android.app.ActivityThread.access$1800(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

##### OS & Version Information
* Android Version: Pixel Android 10
* SDL Android Version: 4.9.1
* Testing Against: Ford SYNC

##### Test Case, Sample Code, and / or Example App

```

			SdlManagerListener listener = new SdlManagerListener() {
				@Override
				public void onStart() {
					// HMI Status Listener
					if(sdlManager.getRegisterAppInterfaceResponse().getVehicleType().getMake().equals("XXXX")){
						Log.d(TAG,"will unregister");
						Intent intent = new Intent();
						intent.setClass(getApplicationContext(), SdlService.class);
						stopService(intent);
						Intent rintent = new Intent();
						rintent.setClass(getApplicationContext(), SdlRouterService.class);
						stopService(rintent);
					}
}

```

**Comment by BrettyWhite** [comment]
Closed with #1176
