### ISSUE TITLE
Android Navigation App Error: Unable to create Virtual Display

### ISSUE THREAD

**Issue by bill-lzb** [smartdevicelink/sdl_java_suite#1212]
[Delete any non-applicable sections, but we may ask for more information. Please reference the [SmartDeviceLink GitHub Best Practices](https://d83tozu1c8tt6.cloudfront.net/media/resources/SDL_GitHub_BestPractices.pdf) for further instructions on how to enter an issue.]

### Bug Report
[Summary]
Android Navigation App cannot start video streaming, the SDK outputs error 'E/VirtualDisplayEncoder: Unable to create Virtual Display.'
※When I use SDL Android SDK 4.6.0, there is no problem.The error occurs when I use SDL Android SDK 4.9.0

##### Reproduction Steps
1. Refer to [Android Guides 10/03/2019 11:49 AM], and write a Navigation app(With Mapbox).
2. Connect the APP to a SDL Emulator 
3. Click the APP icon on the SDL Emlator

##### Expected Behavior
[Some expected behavior]
The video streaming should be successful

##### Observed Behavior
[Some observed behavior]
The following errors were output:
 W/System.err: java.lang.IllegalArgumentException
 W/System.err:     at android.media.MediaCodec.native_configure(Native Method)
 W/System.err:     at android.media.MediaCodec.configure(MediaCodec.java:1967)
 W/System.err:     at android.media.MediaCodec.configure(MediaCodec.java:1896)
 W/System.err:     at com.smartdevicelink.encoder.VirtualDisplayEncoder.prepareVideoEncoder(VirtualDisplayEncoder.java:206)
 W/System.err:     at com.smartdevicelink.encoder.VirtualDisplayEncoder.start(VirtualDisplayEncoder.java:135)
 W/System.err:     at com.smartdevicelink.managers.video.VideoStreamManager.startEncoder(VideoStreamManager.java:309)
 W/System.err:     at com.smartdevicelink.managers.video.VideoStreamManager.access$800(VideoStreamManager.java:80)
 W/System.err:     at com.smartdevicelink.managers.video.VideoStreamManager$1.onServiceStarted(VideoStreamManager.java:115)
 W/System.err:     at com.smartdevicelink.SdlConnection.SdlSession.onProtocolSessionStarted(SdlSession.java:604)
 W/System.err:     at com.smartdevicelink.SdlConnection.SdlConnection$InternalMsgDispatcher.onProtocolSessionStarted(SdlConnection.java:458)
 W/System.err:     at com.smartdevicelink.SdlConnection.SdlConnection.onProtocolSessionStarted(SdlConnection.java:293)
 W/System.err:     at com.smartdevicelink.protocol.AbstractProtocol.handleProtocolSessionStarted(AbstractProtocol.java:166)
 W/System.err:     at com.smartdevicelink.protocol.WiProProtocol$MessageFrameAssembler.handleControlFrame(WiProProtocol.java:535)
 W/System.err:     at com.smartdevicelink.protocol.WiProProtocol$MessageFrameAssembler.handleFrame(WiProProtocol.java:452)
 W/System.err:     at com.smartdevicelink.protocol.WiProProtocol.handlePacketReceived(WiProProtocol.java:327)
 W/System.err:     at com.smartdevicelink.SdlConnection.SdlConnection.onTransportPacketReceived(SdlConnection.java:241)
 W/System.err:     at com.smartdevicelink.transport.SdlTransport.handleReceivedPacket(SdlTransport.java:73)
 W/System.err:     at com.smartdevicelink.transport.TCPTransport$TCPTransportThread.run(TCPTransport.java:455)
 E/VirtualDisplayEncoder: Unable to create Virtual Display.
 W/System.err: java.lang.RuntimeException: java.lang.IllegalStateException: start failed
 W/System.err:     at com.smartdevicelink.encoder.VirtualDisplayEncoder.start(VirtualDisplayEncoder.java:146)
 W/System.err:     at com.smartdevicelink.managers.video.VideoStreamManager.startEncoder(VideoStreamManager.java:309)
 W/System.err:     at com.smartdevicelink.managers.video.VideoStreamManager.access$800(VideoStreamManager.java:80)
 W/System.err:     at com.smartdevicelink.managers.video.VideoStreamManager$1.onServiceStarted(VideoStreamManager.java:115)
 W/System.err:     at com.smartdevicelink.SdlConnection.SdlSession.onProtocolSessionStarted(SdlSession.java:604)
 W/System.err:     at com.smartdevicelink.SdlConnection.SdlConnection$InternalMsgDispatcher.onProtocolSessionStarted(SdlConnection.java:458)
 W/System.err:     at com.smartdevicelink.SdlConnection.SdlConnection.onProtocolSessionStarted(SdlConnection.java:293)
 W/System.err:     at com.smartdevicelink.protocol.AbstractProtocol.handleProtocolSessionStarted(AbstractProtocol.java:166)
 W/System.err:     at com.smartdevicelink.protocol.WiProProtocol$MessageFrameAssembler.handleControlFrame(WiProProtocol.java:535)
 W/System.err:     at com.smartdevicelink.protocol.WiProProtocol$MessageFrameAssembler.handleFrame(WiProProtocol.java:452)
 W/System.err:     at com.smartdevicelink.protocol.WiProProtocol.handlePacketReceived(WiProProtocol.java:327)
 W/System.err:     at com.smartdevicelink.SdlConnection.SdlConnection.onTransportPacketReceived(SdlConnection.java:241)
 W/System.err:     at com.smartdevicelink.transport.SdlTransport.handleReceivedPacket(SdlTransport.java:73)
 W/System.err:     at com.smartdevicelink.transport.TCPTransport$TCPTransportThread.run(TCPTransport.java:455)
 W/System.err: Caused by: java.lang.IllegalStateException: start failed
 W/System.err:     at android.media.MediaCodec.native_start(Native Method)
 W/System.err:     at android.media.MediaCodec.start(MediaCodec.java:2075)
 W/System.err:     at com.smartdevicelink.encoder.VirtualDisplayEncoder.startEncoder(VirtualDisplayEncoder.java:282)
 W/System.err:     at com.smartdevicelink.encoder.VirtualDisplayEncoder.start(VirtualDisplayEncoder.java:142)
 W/System.err: 	... 13 more

##### OS & Version Information
* Android Version: [API Level 26/28]
* SDL Android Version: [4.9.0]
* Testing Against: [A SDL Emulator developed by our company]

**Comment by BrettyWhite** [comment]
Could you also please print out the capabilities that are being returned by the emulator and paste them back here?

```java
		sdlManager.getSystemCapabilityManager().getCapability(SystemCapabilityType.VIDEO_STREAMING, new OnSystemCapabilityListener() {
			@Override
			public void onCapabilityRetrieved(Object capability) {
				VideoStreamingCapability videoStreamingCapability = (VideoStreamingCapability) capability;
				try {
					Log.i(TAG, "onCapabilityRetrieved: "+ videoStreamingCapability.serializeJSON().toString(4));
				} catch (JSONException e) {
					e.printStackTrace();
				}
			}

			@Override
			public void onError(String info) {
				Log.e(TAG, "onError: "+ info);
			}
		});
```

**Comment by bill-lzb** [comment]
the output is:
onCapabilityRetrieved: {
        "maxBitrate": 1000000,
        "preferredResolution": {
            "resolutionWidth": 800,
            "resolutionHeight": 480
        },
        "hapticSpatialDataSupported": true,
        "supportedFormats": [
            {
                "codec": "H264",
                "protocol": "RAW"
            }
        ]
    }

**Comment by joeygrover** [comment]
Would it be possible for you to test against the open source Core + SDL HMI projects or get access to the custom emulator you mentioned? It will help us determine where the issue is happening.

**Comment by joeygrover** [comment]
The issue is that the capability returned states `"maxBitrate": 1000000`, however as stated in the [SDL RPC spec](https://github.com/smartdevicelink/rpc_spec#videostreamingcapability) the unit for this field is in `kbps`. The `VideoStreamingParameters` class converts this into`bps` as the Android class [`MediaFormat` expects bit rate in `bps`](https://developer.android.com/reference/android/media/MediaFormat.html#KEY_BIT_RATE) to pass to the encoder. This causes the bitrate to be set at 1,000,000,000 bps, which is way outside the range the encoder can handle and then throws the `IllegalArgumentException`. More information on supported bitrates can be found in the Android documentation for devices [here](https://source.android.com/compatibility/android-cdd.pdf);

In 4.6, there was a bug in the  `VideoStreamingParameters` that didn't convert from `kbps` to `bps` which has since been fixed. Therefore, the custom emulator you are using needs to update the `maxBitrate` field to the correct units.
