### ISSUE TITLE
SDL unavailable

### ISSUE THREAD

**Issue by AlbertGRMN** [smartdevicelink/sdl_java_suite#1637]
### Bug Report
App can't start streaming after being launched by the HU and will receive an exception saying SDL is unavailable. 

##### Log
12-28 14:55:36.218 24326 14068 I RpcConverter: name  -  OnHMIStatus
12-28 14:55:36.219 24326 14068 I RpcConverter: parameters  -  {systemContext=MAIN, hmiLevel=FULL, audioStreamingState=AUDIBLE}
12-28 14:55:36.219 24326 14068 I RpcConverter: correlationID  -  -1
12-28 14:55:36.219 24326 14068 I SdlProxy: 4.11.1: RpcConverter Attempting to create com.smartdevicelink.proxy.rpc.OnHMIStatus
12-28 14:55:36.221 24326 14068 I SdlProxy: 4.11.1: Updating soft buttons
12-28 14:55:36.221 24326 14068 I SdlProxy: 4.11.1: Sending soft buttons with images
12-28 14:55:36.222 24326 14068 W System.err: com.smartdevicelink.exception.SdlException: SDL is currently unavailable. RPC Requests cannot be sent.
12-28 14:55:36.222 24326 14068 W System.err: SdlExceptionCause: SDL_UNAVAILABLE
12-28 14:55:36.223 24326 14068 W System.err: 	at com.smartdevicelink.proxy.SdlProxyBase.sendRPC(SdlProxyBase.java:4841)
12-28 14:55:36.223 24326 14068 W System.err: 	at com.smartdevicelink.managers.SdlManager$7.sendRPC(SdlManager.java:805)
12-28 14:55:36.223 24326 14068 W System.err: 	at com.smartdevicelink.managers.screen.BaseSoftButtonManager.update(BaseSoftButtonManager.java:518)
12-28 14:55:36.223 24326 14068 W System.err: 	at com.smartdevicelink.managers.screen.BaseSoftButtonManager$3.onNotified(BaseSoftButtonManager.java:160)
12-28 14:55:36.223 24326 14068 W System.err: 	at com.smartdevicelink.proxy.SdlProxyBase.onRPCNotificationReceived(SdlProxyBase.java:2443)
12-28 14:55:36.223 24326 14068 W System.err: 	at com.smartdevicelink.proxy.SdlProxyBase.handleRPCMessage(SdlProxyBase.java:4054)
12-28 14:55:36.223 24326 14068 W System.err: 	at com.smartdevicelink.proxy.SdlProxyBase.dispatchIncomingMessage(SdlProxyBase.java:1981)
12-28 14:55:36.223 24326 14068 W System.err: 	at com.smartdevicelink.proxy.SdlProxyBase.access$2800(SdlProxyBase.java:173)
12-28 14:55:36.223 24326 14068 W System.err: 	at com.smartdevicelink.proxy.SdlProxyBase$3.dispatch(SdlProxyBase.java:982)
12-28 14:55:36.223 24326 14068 W System.err: 	at com.smartdevicelink.proxy.SdlProxyBase$3.dispatch(SdlProxyBase.java:979)
12-28 14:55:36.223 24326 14068 W System.err: 	at com.smartdevicelink.Dispatcher.ProxyMessageDispatcher.handleMessages(ProxyMessageDispatcher.java:74)
12-28 14:55:36.223 24326 14068 W System.err: 	at com.smartdevicelink.Dispatcher.ProxyMessageDispatcher.access$000(ProxyMessageDispatcher.java:38)
12-28 14:55:36.223 24326 14068 W System.err: 	at com.smartdevicelink.Dispatcher.ProxyMessageDispatcher$1.run(ProxyMessageDispatcher.java:52)
12-28 14:55:36.223 24326 14068 W System.err: 	at java.lang.Thread.run(Thread.java:919)
12-28 14:55:36.224 24326 14075 I SdlProxy: 4.11.1: AsynchronousOperation - Starting: CheckChoiceVROptionalOperation (OpId: 239093545, OpThread:pool-20-thread-1, currentThread:pool-20-thread-1, blocked:false, executing:false, finished:false, cancelled:false)
12-28 14:55:36.224 24326 14075 I SdlProxy: 4.11.1: Choice Operation: Executing check vr optional operation
12-28 14:55:36.224 24326 14068 W System.err: com.smartdevicelink.exception.SdlException: SDL is currently unavailable. RPC Requests cannot be sent.

##### OS & Version Information
* Android : Android 9 (Samsung S10)
* SDL Android Version: 4.11.1

##### Test Case, Sample Code, and / or Example App
1. Connect app with HU
2. Launch app and start streaming.

**Comment by joeygrover** [comment]
This is not reproducible with any known setup, therefore please provide the following:

1. You should updated to at least 4.12.2, and hopefully the latest release for all fixes. 4.11 will not receive new fixes.
2. Can you provide the full logs?
3. What app are you using specifically?
4. What Core/hardware are you connecting to?

**Comment by joeygrover** [comment]
Closing due to inactivity.
