### ISSUE TITLE
IllegalArgumentException when starting video stream with custom RPC MTU

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_java_suite#1667]
### Bug Report
When attempting to start a video stream, if Core has a custom MTU value for the RPC service higher than `MAX_QUEUE_SIZE` (262144), an `IllegalArgumentException` is thrown.

##### Reproduction Steps
1. Set `MaximumRpcPayloadSize = 300000` in smartDeviceLink.ini
2. Connect app with NAVIGATION type
3. Activate app and try to start video stream

##### Expected Behavior
Video stream starts without issue

##### Observed Behavior
App crashes with

```
java.lang.IllegalArgumentException
        at java.util.concurrent.LinkedBlockingQueue.<init>(LinkedBlockingQueue.java:229)
        at com.smartdevicelink.streaming.StreamPacketizer.<init>(StreamPacketizer.java:89)
        at com.smartdevicelink.managers.video.VideoStreamManager.startVideoStream(VideoStreamManager.java:1075)
        at com.smartdevicelink.managers.video.VideoStreamManager$1.onServiceStarted(VideoStreamManager.java:131)
        at com.smartdevicelink.session.SdlSession.onServiceStarted(SdlSession.java:172)
        at com.smartdevicelink.protocol.SdlProtocolBase.handleStartServiceACK(SdlProtocolBase.java:1127)
        at com.smartdevicelink.protocol.SdlProtocolBase$MessageFrameAssembler.handleControlFrame(SdlProtocolBase.java:1469)
        at com.smartdevicelink.protocol.SdlProtocolBase$MessageFrameAssembler.handleFrame(SdlProtocolBase.java:1425)
        at com.smartdevicelink.protocol.SdlProtocolBase.handlePacketReceived(SdlProtocolBase.java:719)
        at com.smartdevicelink.protocol.SdlProtocolBase$2.onPacketReceived(SdlProtocolBase.java:1192)
```

##### OS & Version Information
* Android Version: 6.0.1
* SDL Android Version: 5.1.0
* Testing Against: SDL Core 7.1.0, SDL HMI develop branch

**Comment by JulianKast** [comment]
Fixed with #1680
