### ISSUE TITLE
Fatal Exception: java.lang.SecurityException SdlBroadcastReceiver.java line 539

### ISSUE THREAD

**Issue by asheeshs** [smartdevicelink/sdl_java_suite#1700]
### Bug Report
Fatal Crash

```
Fatal Exception: java.lang.SecurityException: Need BLUETOOTH_CONNECT permission
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2418)
       at android.os.Parcel.createException(Parcel.java:2402)
       at android.os.Parcel.readException(Parcel.java:2385)
       at android.os.Parcel.readException(Parcel.java:2327)
       at android.bluetooth.IBluetooth$Stub$Proxy.getState(IBluetooth.java:1759)
       at android.bluetooth.BluetoothAdapter$2.recompute(BluetoothAdapter.java:988)
       at android.bluetooth.BluetoothAdapter$2.recompute(BluetoothAdapter.java:984)
       at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:519)
       at android.bluetooth.BluetoothAdapter.getStateInternal(BluetoothAdapter.java:1015)
       at android.bluetooth.BluetoothAdapter.getState(BluetoothAdapter.java:1042)
       at android.bluetooth.BluetoothAdapter.isEnabled(BluetoothAdapter.java:872)
       at com.smartdevicelink.transport.SdlBroadcastReceiver.isBluetoothConnected(SdlBroadcastReceiver.java:539)
       at com.smartdevicelink.transport.SdlBroadcastReceiver.requestTransportStatus(SdlBroadcastReceiver.java:522)
       at com.smartdevicelink.transport.SdlBroadcastReceiver.access$500(SdlBroadcastReceiver.java:68)
       at com.smartdevicelink.transport.SdlBroadcastReceiver$4.onComplete(SdlBroadcastReceiver.java:458)
       at com.smartdevicelink.util.ServiceFinder.onFinished(ServiceFinder.java:123)
       at com.smartdevicelink.util.ServiceFinder.access$000(ServiceFinder.java:57)
       at com.smartdevicelink.util.ServiceFinder$1.run(ServiceFinder.java:83)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7727)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

##### Reproduction Steps
Seeing crash in Firebase Crashlytics dash, unfortunately no reproduction steps to share.

##### Expected Behavior
No Crash

##### Observed Behavior
Crashing

##### OS & Version Information
* Android Version: 100% Android 11
* SDL Android Version: 4.12.0
* Testing Against: According to crash logs. app was always in background when the crash was seen.

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by joeygrover** [comment]
Including more details always helps our ability to locate and address these issues if possible. Crashing/not crashing is usually unnecessary information in these types of issues so it would be better if there was more specifics.

First, you should update your library to the latest version as soon as possible as bug fixes are very unlikely to make it back to the last release of version 4 of the library. 

Second, the permission listed here has not officially be introduced yet. It will be released with Android 12, please see the Android documentation [here](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH_CONNECT). Since this permission has not yet been released, the library itself is not compatible with it. It is very strange that you are reporting Android 11 devices are throwing this error since technically that permission doesn't exist in that version of Android.  Can you share any information as to what devices these are?

**Comment by asheeshs** [comment]
@joeygrover I agree with you that Crashing/no crashing doesn't help but I shared whatever information I had. 

Pixel 5 is the device.

**Comment by joeygrover** [comment]
@asheeshs That's very odd. Do you know if Firebase Crashlytics will report SDKs greater than 11? Maybe someone has a Pixel 5 with the developer preview installed, but Crashlytics just reports it as Android 11. Otherwise I am not sure how this could happen in the real world.

While this isn't _technically_ an issue yet since Android 12 isn't released and we don't claim to be compatible yet, it will stay open because we do need to handle this for the upcoming Android release and will track a pull request to it when one is ready.

**Comment by joeljfischer** [comment]
Closed due to inactivity
