### ISSUE TITLE
NPE crash in SdlDeviceListener

### ISSUE THREAD

**Issue by spstreckfus** [smartdevicelink/sdl_java_suite#1780]
### Bug Report
Crash in `SdlDeviceListener.notifyConnection()` on line 262. Attempting to call `sdlListener.bluetoothTransport.stop()` when `bluetoothTransport` value is null.

##### Reproduction Steps
Unfortunately unable to reproduce at the moment. This crash came from our Crashlytics logs and has only been observed after moving from 5.2 to 5.3.

##### OS & Version Information
* Android Version: Seeing this in Android 9, 10, 11, and 12
* SDL Android Version: 5.3
* Testing Against: No tests as this came from Crashlytics logs.

##### Test Case, Sample Code, and / or Example App
None currently available.

##### Crash Log
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.smartdevicelink.transport.MultiplexBluetoothTransport.stop()' on a null object reference
       at com.smartdevicelink.transport.utl.SdlDeviceListener$TransportHandler.notifyConnection(SdlDeviceListener.java:262)
       at com.smartdevicelink.transport.utl.SdlDeviceListener$TransportHandler.onPacketRead(SdlDeviceListener.java:223)
       at com.smartdevicelink.transport.utl.SdlDeviceListener$TransportHandler.handleMessage(SdlDeviceListener.java:183)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by JulianKast** [comment]
This will be fixed in our 5.4.0 release this april with #1789
