### ISSUE TITLE
NPE crash in BaseLifecycleManager

### ISSUE THREAD

**Issue by spstreckfus** [smartdevicelink/sdl_java_suite#1781]
### Bug Report
Crash in `BaseLifecycleManager.sendRPCMessagePrivate()` on line 871. Calling `session.sendMessage()` when value of `session` is null.

##### Reproduction Steps
Unfortunately unable to reproduce at the moment. This crash came from our Crashlytics logs and has only been observed after moving from SDL Android 5.2 to 5.3.

##### OS & Version Information
* Android Version: Seeing this in Android 9, 10, 11, and 12
* SDL Android Version: 5.3
* Testing Against: No tests as this came from Crashlytics logs.

##### Test Case, Sample Code, and / or Example App
None currently available.

##### Crash Log
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.smartdevicelink.session.BaseSdlSession.sendMessage(com.smartdevicelink.protocol.ProtocolMessage)' on a null object reference
       at com.smartdevicelink.managers.lifecycle.BaseLifecycleManager.sendRPCMessagePrivate(BaseLifecycleManager.java:871)
       at com.smartdevicelink.managers.lifecycle.BaseLifecycleManager.access$200(BaseLifecycleManager.java:105)
       at com.smartdevicelink.managers.lifecycle.BaseLifecycleManager$4.onSessionStarted(BaseLifecycleManager.java:987)
       at com.smartdevicelink.session.SdlSession.onServiceStarted(SdlSession.java:162)
       at com.smartdevicelink.protocol.SdlProtocolBase.handleStartServiceACK(SdlProtocolBase.java:1122)
       at com.smartdevicelink.protocol.SdlProtocolBase$MessageFrameAssembler.handleControlFrame(SdlProtocolBase.java:1464)
       at com.smartdevicelink.protocol.SdlProtocolBase$MessageFrameAssembler.handleFrame(SdlProtocolBase.java:1420)
       at com.smartdevicelink.protocol.SdlProtocolBase.handlePacketReceived(SdlProtocolBase.java:715)
       at com.smartdevicelink.protocol.SdlProtocolBase$2.onPacketReceived(SdlProtocolBase.java:1187)
       at com.smartdevicelink.transport.TransportManager$LegacyBluetoothHandler.handleMessage(TransportManager.java:523)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6981)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by bilal-alsharifi** [comment]
Thanks @spstreckfus, for reporting the issue. I tried to reproduce the issue but I couldn't. It is not easy to know what exactly led to that situation without reproduction steps but my guess is that for some reason `SdlManager.dispose()` is getting called before the app fully registers. If `dispose()` is called, it will call `BaseLifecycleManager.stop()` which sets `session` to `null` then if the app tries to send `RegisterAppInterface` request, that will crash because `sendRPCMessagePrivate()` will be called on a `null` session. We can make a PR to wrap the `session.sendMessage(pm)` with a `null` check which should prevent the crash from happening.
