### ISSUE TITLE
Video auto restarts streaming regardless if HMI level is streamable 

### ISSUE THREAD

**Issue by JulianKast** [smartdevicelink/sdl_java_suite#1807]
### Bug Summary

Video auto restarts streaming regardless if HMI level is streamable.

### Reproduction Steps

1. Stream video to sdl_HMI
2. Exit out of the app using voice
3. Open app and start streaming again

Expected Behavior:
Video should steam at the end

Observed Behavior:
Video does not stream

### Android Version(s)

12

### Android Device(s)

Pixel 3, Pixel 4a, Samsung galaxy s8+

### sdl_java_suite Version

RC_5.4.0

### Testing Environment(s)

```markdown
Sdl Core 8.1 with sdl hmi
```

### Relevant log output

```shell
2022-04-08 17:49:42.953 31237-31237/io.livio.sdltestsuite.app1 I/SdlService: onNotified: HMILevel: NONE WindowID: 0
2022-04-08 17:49:42.953 31237-31237/io.livio.sdltestsuite.app1 I/SdlService: SdlSecurity onEncryptionServiceUpdated: serviceType: NAV, encrypted: false, errors: null
2022-04-08 17:49:42.953 31237-31237/io.livio.sdltestsuite.app1 I/BaseEncryptionLifecycleManager: RC_5.4.0: onServiceEnded, session Type: NAV
2022-04-08 17:49:42.959 31237-31335/io.livio.sdltestsuite.app1 W/System.err: java.lang.InterruptedException
2022-04-08 17:49:42.959 31237-31335/io.livio.sdltestsuite.app1 W/System.err:     at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2042)
2022-04-08 17:49:42.959 31237-31335/io.livio.sdltestsuite.app1 W/System.err:     at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2076)
2022-04-08 17:49:42.959 31237-31335/io.livio.sdltestsuite.app1 W/System.err:     at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
2022-04-08 17:49:42.959 31237-31335/io.livio.sdltestsuite.app1 W/System.err:     at com.smartdevicelink.streaming.StreamPacketizer.run(StreamPacketizer.java:144)
2022-04-08 17:49:42.959 31237-31335/io.livio.sdltestsuite.app1 W/System.err:     at java.lang.Thread.run(Thread.java:920)
2022-04-08 17:49:42.975 31237-31289/io.livio.sdltestsuite.app1 I/MultiplexTcpTransport: RC_5.4.0: Packet formed, sending off
2022-04-08 17:49:42.985 31237-31237/io.livio.sdltestsuite.app1 W/SdlProtocol: RC_5.4.0: Cannot start an unprotected service of type 11. Session 1 already has an unprotected service of type 11
2022-04-08 17:49:42.986 31237-31237/io.livio.sdltestsuite.app1 I/SdlService: SdlSecurity onEncryptionServiceUpdated: serviceType: NAV, encrypted: false, errors: onServiceError: Service start NAK received for service type NAV
2022-04-08 17:49:42.986 31237-31237/io.livio.sdltestsuite.app1 E/BaseEncryptionLifecycleManager: RC_5.4.0: onServiceError, session Type: NAV, reason: Service start NAK received for service type NAV
2022-04-08 17:49:42.986 31237-31237/io.livio.sdltestsuite.app1 E/VideoStreamManager: RC_5.4.0: Unable to start video service: Service start NAK received for service type NAV
2022-04-08 17:49:42.986 31237-31289/io.livio.sdltestsuite.app1 I/MultiplexTcpTransport: RC_5.4.0: Packet formed, sending off
2022-04-08 17:49:42.991 31237-31237/io.livio.sdltestsuite.app1 I/SdlService: SdlSecurity onEncryptionServiceUpdated: serviceType: NAV, encrypted: false, errors: null
2022-04-08 17:49:42.991 31237-31237/io.livio.sdltestsuite.app1 I/BaseEncryptionLifecycleManager: RC_5.4.0: onServiceEnded, session Type: NAV
2022-04-08 17:49:43.006 31237-31289/io.livio.sdltestsuite.app1 I/MultiplexTcpTransport: RC_5.4.0: Packet formed, sending off
2022-04-08 17:49:43.034 31237-31237/io.livio.sdltestsuite.app1 W/SdlProtocol: RC_5.4.0: Service type: 11 disallowed with current HMI level
2022-04-08 17:49:43.035 31237-31237/io.livio.sdltestsuite.app1 I/SdlService: SdlSecurity onEncryptionServiceUpdated: serviceType: NAV, encrypted: false, errors: onServiceError: Service start NAK received for service type NAV
2022-04-08 17:49:43.035 31237-31237/io.livio.sdltestsuite.app1 E/BaseEncryptionLifecycleManager: RC_5.4.0: onServiceError, session Type: NAV, reason: Service start NAK received for service type NAV
2022-04-08 17:49:43.035 31237-31237/io.livio.sdltestsuite.app1 E/VideoStreamManager: RC_5.4.0: Unable to start video service: Service start NAK received for service type NAV
2022-04-08 17:49:44.686 31237-31338/io.livio.sdltestsuite.app1 D/CCodecBufferChannel: [c2.qti.avc.encoder#430] DEBUG: elapsed: n=8 [in=0 pipeline=0 out=4]
2022-04-08 17:49:47.987 31237-31338/io.livio.sdltestsuite.app1 D/CCodecBufferChannel: [c2.qti.avc.encoder#430] DEBUG: elapsed: n=8 [in=0 pipeline=0 out=4]
2022-04-08 17:49:49.940 31237-31289/io.livio.sdltestsuite.app1 I/MultiplexTcpTransport: RC_5.4.0: Packet formed, sending off
2022-04-08 17:49:49.943 31237-31237/io.livio.sdltestsuite.app1 I/RpcConverter: RC_5.4.0: name  -  OnHMIStatus
2022-04-08 17:49:49.943 31237-31237/io.livio.sdltestsuite.app1 I/RpcConverter: RC_5.4.0: parameters  -  {windowID=0, systemContext=MAIN, hmiLevel=FULL, videoStreamingState=STREAMABLE, audioStreamingState=AUDIBLE}
2022-04-08 17:49:49.943 31237-31237/io.livio.sdltestsuite.app1 I/RpcConverter: RC_5.4.0: correlationID  -  -1
2022-04-08 17:49:49.943 31237-31237/io.livio.sdltestsuite.app1 I/RpcConverter: RC_5.4.0:  Attempting to create com.smartdevicelink.proxy.rpc.OnHMIStatus
2022-04-08 17:49:49.944 31237-31237/io.livio.sdltestsuite.app1 I/Lifecycle Manager: RC_5.4.0: RPC received - notification
2022-04-08 17:49:49.945 31237-31237/io.livio.sdltestsuite.app1 I/Lifecycle Manager: RC_5.4.0: on hmi status
2022-04-08 17:49:49.945 31237-31237/io.livio.sdltestsuite.app1 I/Lifecycle Manager: RC_5.4.0: onRPCNotificationReceived - OnHMIStatus
2022-04-08 17:49:49.949 31237-31237/io.livio.sdltestsuite.app1 I/BaseAlertManager: RC_5.4.0: Starting the transaction queue
2022-04-08 17:49:49.950 31237-31237/io.livio.sdltestsuite.app1 I/BaseSoftButtonManager: RC_5.4.0: Starting the transaction queue
2022-04-08 17:49:49.951 31237-31237/io.livio.sdltestsuite.app1 I/TextAndGraphicManager: RC_5.4.0: Starting the transaction queue
2022-04-08 17:49:49.951 31237-31237/io.livio.sdltestsuite.app1 I/BaseMenuManager: RC_5.4.0: Starting the transaction queue
2022-04-08 17:49:49.952 31237-31237/io.livio.sdltestsuite.app1 I/BaseVoiceCommandManager: RC_5.4.0: Starting the transaction queue
2022-04-08 17:49:49.953 31237-31237/io.livio.sdltestsuite.app1 I/SdlService: onNotified: HMILevel: FULL WindowID: 0
2022-04-08 17:49:51.082 31237-31237/io.livio.sdltestsuite.app1 I/ViewRootImpl@61c6a6a[MainActivity]: ViewPostIme pointer 0
2022-04-08 17:49:51.130 31237-31237/io.livio.sdltestsuite.app1 I/ViewRootImpl@61c6a6a[MainActivity]: ViewPostIme pointer 1
2022-04-08 17:49:51.333 31237-31338/io.livio.sdltestsuite.app1 D/CCodecBufferChannel: [c2.qti.avc.encoder#430] DEBUG: elapsed: n=8 [in=0 pipeline=0 out=4]
2022-04-08 17:49:52.490 31237-31237/io.livio.sdltestsuite.app1 I/ViewRootImpl@61c6a6a[MainActivity]: ViewPostIme pointer 0
2022-04-08 17:49:52.564 31237-31237/io.livio.sdltestsuite.app1 I/ViewRootImpl@61c6a6a[MainActivity]: ViewPostIme pointer 1
2022-04-08 17:49:52.571 31237-31237/io.livio.sdltestsuite.app1 I/MainActivity: Starting : PlayVideo (RAW) ...
2022-04-08 17:49:52.574 31237-31237/io.livio.sdltestsuite.app1 V/Toast: show: caller = io.livio.sdltestsuite.activities.MainActivity.onNavigationItemSelected:524 
2022-04-08 17:49:52.574 31237-31237/io.livio.sdltestsuite.app1 V/Toast: show: focusDisplayId = 0, isFocusInDesktop = false mCustomDisplayId=-1 isDexDualMode=false
2022-04-08 17:49:52.574 31237-31237/io.livio.sdltestsuite.app1 V/Toast: show: isActivityContext = false
2022-04-08 17:49:52.578 31237-31237/io.livio.sdltestsuite.app1 I/TestRunner: testVideoStreamManager: 192
2022-04-08 17:49:52.578 31237-31237/io.livio.sdltestsuite.app1 I/TestRunner: SETTING_UP ; 0
2022-04-08 17:49:52.578 31237-31237/io.livio.sdltestsuite.app1 I/TestRunner: READY  48
2022-04-08 17:49:52.578 31237-31237/io.livio.sdltestsuite.app1 I/TestRunner: LIMITED  80
2022-04-08 17:49:52.578 31237-31237/io.livio.sdltestsuite.app1 I/TestRunner: SHUTDOWN  128
2022-04-08 17:49:52.578 31237-31237/io.livio.sdltestsuite.app1 I/TestRunner: ERROR  192
2022-04-08 17:49:52.580 31237-31237/io.livio.sdltestsuite.app1 I/TestRunner: Trying to start video streaming
2022-04-08 17:49:52.580 31237-31237/io.livio.sdltestsuite.app1 E/TestRunner: Failed to start video streaming manager
```
```

**Comment by joeljfischer** [comment]
Closed by #1808
