### ISSUE TITLE
PolicyFetcher Exception on old module

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_java_suite#1813]
### Bug Summary

The PolicyFetcher class throws an exception attempting to perform a policy update on older modules (Sync 2.0). This happens every attempt, and is likely some stricter policy being enforced on the phone or potentially an end point issue.

### Reproduction Steps

1. Connect phone to older module
2. Connect SDL
3. Observe logs

Expected Behavior:

Policy update occurs without issue.

Observed Behavior:

Policy update experiences an exception thrown and no update was made.

### Which projects have you seen this bug on?

Android

### Android Version(s)

11

### Android Device(s)

Pixel 2 XL

### sdl_java_suite Version

5.2.0

### Testing Environment(s)

```markdown
- Ford TDK 2.0
```

### Relevant log output

```shell
2022-06-15 11:18:28.108 951-1445/com.sdl.hellosdlandroid E/PoliciesFetcher: 5.4.0: sendSystemRequestToUrl: IOException: 
    javax.net.ssl.SSLPeerUnverifiedException: Hostname (REDACTED) not verified:
        certificate: sha1/(REDACTED)
        DN: CN=*.(REDACTED),O=M(REDACTED),L=(REDACTED)S
        subjectAltNames: (REDACTED)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:205)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
        at com.smartdevicelink.managers.lifecycle.PoliciesFetcher.fetchPolicies(PoliciesFetcher.java:162)
        at com.smartdevicelink.managers.lifecycle.BaseLifecycleManager$3$1.run(BaseLifecycleManager.java:487)
```

**Comment by joeljfischer** [comment]
Closed as won't fix
