### ISSUE TITLE
TransportBroker NPE

### ISSUE THREAD

**Issue by JulianKast** [smartdevicelink/sdl_java_suite#1881]
### Description

TransportBroker.shutDownRouterServiceMessenger hitting NPE, likely due to `routerServiceMessenger` being set to null before we close `routerServiceMessageEmitter`. This NPE was hit by accident, testing custom RS logic with an incorrect app. The code referenced with this NPE has not been released yet and is only on the RC.

```
E  FATAL EXCEPTION: RouterServiceMessageEmitter
                                      Process: com.sdl.hellosdlandroid, PID: 17777
                                      java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder android.os.Messenger.getBinder()' on a null object reference
                                      at com.smartdevicelink.transport.TransportBroker.sendMessageToRouterService(TransportBroker.java:153)
                                      at com.smartdevicelink.transport.TransportBroker$1$1.onMessageToSend(TransportBroker.java:116)
                                      at com.smartdevicelink.transport.RouterServiceMessageEmitter.run(RouterServiceMessageEmitter.java:32)
```

**Comment by joeygrover** [comment]
Closed with #1882
