### ISSUE TITLE
NPE at SdlProtocol.java line 1132

### ISSUE THREAD

**Issue by asheeshs** [smartdevicelink/sdl_java_suite#946]
### Bug Report
Crash at SdlProtocol.java line 1132

##### Reproduction Steps
Not sure. Captured in Fabric (Crashlytics, see the stack trace below:
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.smartdevicelink.transport.TransportManager.close(long)' on a null object reference
       at com.smartdevicelink.protocol.SdlProtocol$2.onTransportDisconnected(SdlProtocol.java:1132)
       at com.smartdevicelink.transport.TransportManager$TransportBrokerImpl.onHardwareDisconnected(TransportManager.java:263)
       at com.smartdevicelink.transport.TransportBroker$1.onServiceDisconnected(TransportBroker.java:122)
       at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1228)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1242)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5491)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)`

##### Expected Behavior
Sdl shoud not crash.

##### Observed Behavior
Crash is seen.

##### OS & Version Information
* Android Version: 6.0.1, Device name: Droid Turbo, 
* SDL Android Version: 4.7.2
* Testing Against: Saw the crash in Fabric(Crashlytics)

##### Test Case, Sample Code, and / or Example App
NA

**Comment by BrettyWhite** [comment]
Fixed via #1055
